development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: hourschool_v2_development2
  pool: 5
  host: localhost
  # username: root


test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: hourschool_v2_test
  pool: 5
  host: localhost
  # username: root

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: hourschool_v2_production
  pool: 5
  host: localhost
  # username: root
