development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: hourschool_v2_development
  pool: 5
  # username: root
  password:


test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: hourschool_v2_test
  pool: 5
  # username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: hourschool_v2_production
  pool: 5
  # username: root
  password:
  socket: /tmp/mysql.sock
